version: '3.8'

services:
  vocal-api:
    build: .
    container_name: vocal-extractor-api
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
      - VERCEL_BLOB_READ_WRITE_TOKEN=${VERCEL_BLOB_READ_WRITE_TOKEN}
      - VERCEL_BLOB_STORE_ID=${VERCEL_BLOB_STORE_ID:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G 